### ISSUE TITLE
Missing Reader V0.0.5 kicad pcb for 4 layer board

### ISSUE THREAD

**Issue by R0G-DEV** [cjinn/cantech-reader#2]
Hey @cjinn, I was looking through your open source library but cannot find the KiCad project for revision 0.0.5. The 4 Layer board.

Can you share the 4 layer board too? Thanks.

<img src="https://user-images.githubusercontent.com/32370138/136054606-9a52cd16-bc0a-46f5-9012-096cf78be2fe.png" alt="4 Layer V0.0.5]" width="150px">

<img src="https://user-images.githubusercontent.com/32370138/136055090-de60edfa-724e-4362-b444-a84c785b05d9.png" alt="4 Layer V0.0.5]" width="150px">

**Comment by cjinn** [comment]
I found issues with the 4-layer board and wasn't sure if the problem is with my schematic or gerber files.  I decided to go with a simpler (and cheaper) 2-layer to troubleshoot the initial design. From the 2-layer design, I found the flaws in my design and will probably try a simpler design.
